version: '3.4'

services:
  app:
    platform: linux/x86_64
    container_name: go-todo-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:8080
    volumes:
      - .:/go/src/app
    tty: true
    environment:
      - DATABASE_HOST=mysql-db
      - DATABASE_PORT=3306
      - DATABASE_NAME=todo-app
      - DATABASE_USER=todo-app
      - DATABASE_PASSWORD=todo-app
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: mysql-db
    ports:
      - 3306:3306
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo-app
      MYSQL_USER: todo-app
      MYSQL_PASSWORD: todo-app
      TZ: 'Asia/Tokyo'
